---
abstract: 'Ocs-Inventory unified Agent for UNIX and Linux'
author: ~
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ocsinventory-Agent
no_index:
  directory:
    - inc
recommends:
  Compress::Zlib: 0
  Net::IP: 0
  Proc::Daemon: 0
  Proc::PID::File: 0
requires:
  Digest::MD5: 0
  File::Temp: 0
  LWP: 0
  XML::Simple: 0
  perl: 5.6.0
version: 1.0.1
