abstract: Ocs-Iventory unified Agent for UNIX and Linux
distribution_type: module
generated_by: Module::Install version 0.64
license: gpl
name: Ocsinventory-Agent
no_index:
  directory:
    - inc
    - t
recommends:
  Compress::Zlib: 0
  Proc::Daemon: 0
requires:
  Digest::MD5: 0
  File::Temp: 0
  LWP: 0
  Net::IP: 0
  XML::Simple: 0
  perl: 5.6.0
version: 0.0.8.1
